/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.tda.lista.Login.CuentaLogin;
import controlador.tda.lista.exception.PosicionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Cuenta;

/**
 *
 * @author johnny
 */
public class VistaRegistrar extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistrar
     */
    public VistaRegistrar() {
        initComponents();
    }

    public void CrearCuenta() {
        if (txtNombre.getText().isEmpty()
                //                && txtApellido.getText().isEmpty()
                //                && txtUsuario.getText().isEmpty()
                && txtClave.getText().isEmpty()
                && txtRepClave.getText().equals(txtClave.getText())) {
//                && txtCedula.getText().isEmpty()
//                && TxtDirecion.getText().isEmpty()
//                && txtCorreo.getText().isEmpty()
//                && txtTelefono.getText().isEmpty()) {
            Cuenta cuenta = new Cuenta(txtUsuario.getText(), txtRepClave.getText());
            if (CuentaLogin.insertar(cuenta)) {
                JOptionPane.showMessageDialog(this, "Usuario Registrdo.");
                System.out.println("Registrado");
            } else {
                JOptionPane.showMessageDialog(this, "Usuario Existente.");
                System.out.println("No Registrado");
            }
        }
    }

    public void Modificardatos() {
        if (txtNombre.getText().isEmpty()
                && txtApellido.getText().isEmpty()
                && txtUsuario.getText().isEmpty()
                && txtClave.getText().isEmpty()
                && txtRepClave.getText().equals(txtClave.getText())
                && txtCedula.getText().isEmpty()
                && TxtDirecion.getText().isEmpty()
                && txtCorreo.getText().isEmpty()
                && txtTelefono.getText().isEmpty()) {
            Cuenta cuenta = new Cuenta(txtUsuario.getText(), txtRepClave.getText());
            if (CuentaLogin.modificar(cuenta)) {
                JOptionPane.showMessageDialog(this, "Usuario Modificado.");
            } else {
                JOptionPane.showMessageDialog(this, "Usuario No Existe.");
            }
        }
    }

    public void EliminarD() throws PosicionException {
        if (txtUsuario.getText().isEmpty()) {
            if (CuentaLogin.eliminar(txtUsuario.getText())) {
                JOptionPane.showMessageDialog(this, "Usuario Eliminado.");
            } else {
                JOptionPane.showMessageDialog(this, "Usuario No Eliminado.");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtDirecion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRepClave = new javax.swing.JPasswordField();
        butCrear = new javax.swing.JButton();
        butEliminar = new javax.swing.JButton();
        butModificar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        jLabel1.setText("Registrar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 140, -1));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 189, -1));

        jLabel2.setText("Cedula");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 51, -1));

        jLabel3.setText("Nombres");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 187, -1));

        jLabel4.setText("Apellidos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 187, -1));

        jLabel5.setText("Direccion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        jPanel1.add(TxtDirecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 189, -1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 189, -1));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 184, -1));

        jLabel8.setText("Correo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel9.setText("Telefono");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jLabel10.setText("Usuario");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 187, -1));
        jPanel1.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 187, -1));

        jLabel11.setText("Clave");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel12.setText("Confirmar clave");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));
        jPanel1.add(txtRepClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 233, -1));

        butCrear.setText("Crear Cuenta");
        butCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCrearActionPerformed(evt);
            }
        });
        jPanel1.add(butCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        butEliminar.setText("Eliminar");
        butEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(butEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));

        butModificar.setText("Modificar");
        butModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butModificarActionPerformed(evt);
            }
        });
        jPanel1.add(butModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        jButton1.setText("close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 16));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butModificarActionPerformed
        Modificardatos();
    }//GEN-LAST:event_butModificarActionPerformed

    private void butCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCrearActionPerformed
        CrearCuenta();
    }//GEN-LAST:event_butCrearActionPerformed

    private void butEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEliminarActionPerformed
        try {
            EliminarD();
        } catch (PosicionException ex) {
            Logger.getLogger(VistaRegistrar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtDirecion;
    private javax.swing.JButton butCrear;
    private javax.swing.JButton butEliminar;
    private javax.swing.JButton butModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtRepClave;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
